import { NivelRiesgo, Product } from '../entities/product.entity';

export const PRODUCTS: Product[] = [
  {
    id: 'p1',
    nombre: 'Bono de Productividad Empresarial',
    codigo: 'BPP-2030',
    tipo: 'Bono',
    descripcionCorta: 'Bono corporativo ligado a indicadores de productividad.',
    descripcionLarga:
      'Bono de renta fija emitido por compañías consolidadas, con cupón variable ajustado a su eficiencia operativa.',
    moneda: 'USD',
    riesgo: NivelRiesgo.ALTO,
    tasaInteresAnual: 3.5,
    plazoMeses: 60,
    liquidezDias: 30,
    montoMinimo: 500,
    destacado: true,
    tags: ['bono', 'renta fija', 'corporativo'],
  },
  {
    id: 'p2',
    nombre: 'Fondo de Innovación y Startups Globales',
    codigo: 'FIINC-PLUS',
    tipo: 'Fondo de Inversión',
    descripcionCorta:
      'Fondo que invierte en startups tecnológicas de alto potencial.',
    descripcionLarga:
      'Fondo de renta variable enfocado en empresas jóvenes con modelos escalables y riesgo elevado.',
    moneda: 'USD',
    riesgo: NivelRiesgo.ALTO,
    rentabilidadEsperadaAnual: 18,
    liquidezDias: 7,
    montoMinimo: 1000,
    destacado: true,
    tags: ['fondo', 'startups', 'tecnología'],
  },
  {
    id: 'p3',
    nombre: 'Acciones de Mercados Frontera Global',
    codigo: 'AUPA-MULTI',
    tipo: 'Acción',
    descripcionCorta:
      'Cartera diversificada en mercados frontera y emergentes.',
    descripcionLarga:
      'Acciones de empresas listadas en mercados emergentes con oportunidades de crecimiento pero alta volatilidad.',
    moneda: 'EUR',
    riesgo: NivelRiesgo.ALTO,
    rentabilidadEsperadaAnual: 25,
    liquidezDias: 2,
    montoMinimo: 200,
    destacado: false,
    tags: ['acciones', 'emergentes', 'crecimiento'],
  },
  {
    id: 'p4',
    nombre: 'Depósito a Plazo Escalonado con Bonificación',
    codigo: 'DPFC-12M',
    tipo: 'Depósito a Plazo',
    descripcionCorta:
      'Depósito con bonificación si no hay retiros anticipados.',
    descripcionLarga:
      'Ofrece una tasa base garantizada más una bonificación final si el capital se mantiene hasta el vencimiento.',
    moneda: 'USD',
    riesgo: NivelRiesgo.MEDIO,
    tasaInteresAnual: 8,
    plazoMeses: 12,
    liquidezDias: 60,
    montoMinimo: 300,
    destacado: false,
    tags: ['depósito', 'ahorro'],
  },
  {
    id: 'p5',
    nombre: 'Índice Cripto de Sentimiento de Mercado',
    codigo: 'EMTC-CRYPTO',
    tipo: 'Fondo Cripto',
    descripcionCorta:
      'Replica un índice que combina cripto + sentimiento de mercado.',
    descripcionLarga:
      'Producto que mezcla criptomonedas líderes con modelos cuantitativos basados en sentimiento.',
    moneda: 'USD',
    riesgo: NivelRiesgo.ALTO,
    rentabilidadEsperadaAnual: 40,
    liquidezDias: 0,
    montoMinimo: 50,
    destacado: true,
    tags: ['crypto', 'índice'],
  },
  {
    id: 'p6',
    nombre: 'Seguro de Protección Financiera Personal',
    codigo: 'SCDD-PRO',
    tipo: 'Seguro',
    descripcionCorta: 'Seguro que cubre pérdida de ingresos y asesoría básica.',
    descripcionLarga:
      'Incluye orientación financiera, cobertura ante desempleo e incapacidad temporal.',
    moneda: 'USD',
    riesgo: NivelRiesgo.BAJO,
    liquidezDias: 5,
    montoMinimo: 100,
    destacado: false,
    tags: ['seguro', 'protección'],
  },
  {
    id: 'p7',
    nombre: 'ETF de Metas de Largo Plazo',
    codigo: 'ETSD-LIFE',
    tipo: 'ETF',
    descripcionCorta:
      'ETF balanceado para objetivos como jubilación o estudios.',
    descripcionLarga:
      'Mezcla bonos soberanos, corporativos y acciones globales para inversión a 10–20 años.',
    moneda: 'USD',
    riesgo: NivelRiesgo.MEDIO,
    rentabilidadEsperadaAnual: 10,
    liquidezDias: 1,
    montoMinimo: 250,
    destacado: true,
    tags: ['ETF', 'largo plazo'],
  },
  {
    id: 'p8',
    nombre: 'Swap de Actividad Económica Regional',
    codigo: 'SCF-SEASON',
    tipo: 'Derivado',
    descripcionCorta: 'Cobertura ante ciclos económicos regionales.',
    descripcionLarga:
      'Permite intercambiar exposición a crecimiento entre regiones o sectores económicos.',
    moneda: 'USD',
    riesgo: NivelRiesgo.MEDIO,
    rentabilidadEsperadaAnual: 12,
    liquidezDias: 10,
    montoMinimo: 800,
    destacado: false,
    tags: ['derivado', 'cobertura'],
  },
  {
    id: 'p9',
    nombre: 'Cuenta Corriente con Programa de Beneficios',
    codigo: 'KARMA-CC',
    tipo: 'Cuenta Corriente',
    descripcionCorta: 'Cuenta sin costo de mantenimiento y con recompensas.',
    descripcionLarga:
      'Reduce comisiones si se mantiene saldo mínimo y se cumple disciplina financiera.',
    moneda: 'USD',
    riesgo: NivelRiesgo.BAJO,
    tasaInteresAnual: 0.5,
    liquidezDias: 0,
    montoMinimo: 0,
    destacado: false,
    tags: ['cuenta', 'beneficios'],
  },
  {
    id: 'p10',
    nombre: 'Plan de Jubilación Internacional 2060',
    codigo: 'RET-MARS-2060',
    tipo: 'Plan de Jubilación',
    descripcionCorta: 'Plan global de ahorro para retiro en 30+ años.',
    descripcionLarga:
      'Invierte en bonos, acciones y activos alternativos con opciones de portabilidad internacional.',
    moneda: 'USD',
    riesgo: NivelRiesgo.MEDIO,
    rentabilidadEsperadaAnual: 9,
    plazoMeses: 420,
    liquidezDias: 90,
    montoMinimo: 1500,
    destacado: true,
    tags: ['jubilación', 'multipaís'],
  },

  /* 11–20 */
  {
    id: 'p11',
    nombre: 'Certificado de Estabilidad de Ingresos',
    codigo: 'CEE-TRUST',
    tipo: 'Certificado',
    descripcionCorta: 'Tasa preferente para clientes con ingresos estables.',
    descripcionLarga:
      'Renta fija con recompensa por buen historial crediticio y estabilidad laboral.',
    moneda: 'USD',
    riesgo: NivelRiesgo.MEDIO,
    tasaInteresAnual: 6,
    plazoMeses: 18,
    liquidezDias: 15,
    montoMinimo: 400,
    destacado: false,
    tags: ['certificado', 'ingresos'],
  },
  {
    id: 'p12',
    nombre: 'Crédito Hipotecario Flexible Global',
    codigo: 'CHD-X',
    tipo: 'Crédito Hipotecario',
    descripcionCorta: 'Hipoteca con cambios de moneda y plazo flexible.',
    descripcionLarga:
      'Financiamiento con conversión de moneda y reprogramación según ingresos.',
    moneda: 'USD',
    riesgo: NivelRiesgo.ALTO,
    tasaInteresAnual: 11,
    plazoMeses: 360,
    liquidezDias: 0,
    montoMinimo: 50000,
    destacado: false,
    tags: ['hipoteca', 'vivienda'],
  },
  {
    id: 'p13',
    nombre: 'Token de Hábitos Financieros',
    codigo: 'MOT-COIN',
    tipo: 'Token',
    descripcionCorta:
      'Tokens como recompensa por buen comportamiento financiero.',
    descripcionLarga:
      'Se obtiene por ahorro constante, pagos puntuales y uso responsable de productos.',
    moneda: 'MTC',
    riesgo: NivelRiesgo.ALTO,
    rentabilidadEsperadaAnual: 32,
    liquidezDias: 0,
    montoMinimo: 20,
    destacado: false,
    tags: ['token', 'recompensas'],
  },
  {
    id: 'p14',
    nombre: 'Plan de Ahorro Objetivos Futuro',
    codigo: 'TTS-PLAN',
    tipo: 'Plan de Ahorro',
    descripcionCorta: 'Ahorro programado con metas claras.',
    descripcionLarga:
      'Permite fijar objetivos y programar aportaciones automáticas con bonificaciones.',
    moneda: 'EUR',
    riesgo: NivelRiesgo.BAJO,
    tasaInteresAnual: 2.5,
    plazoMeses: 240,
    liquidezDias: 60,
    montoMinimo: 100,
    destacado: false,
    tags: ['ahorro', 'objetivos'],
  },
  {
    id: 'p15',
    nombre: 'Microbonos de Consumo Masivo',
    codigo: 'CAF-BOND',
    tipo: 'Bono',
    descripcionCorta: 'Bonos accesibles emitidos por empresas de consumo.',
    descripcionLarga:
      'Renta fija al alcance de pequeños inversionistas, ideal para diversificar.',
    moneda: 'USD',
    riesgo: NivelRiesgo.MEDIO,
    tasaInteresAnual: 7,
    plazoMeses: 36,
    liquidezDias: 30,
    montoMinimo: 50,
    destacado: false,
    tags: ['bono', 'consumo'],
  },
  {
    id: 'p16',
    nombre: 'Fondo de Ocio y Entretenimiento Global',
    codigo: 'FUN-FND',
    tipo: 'Fondo de Inversión',
    descripcionCorta: 'Expone a gaming, streaming y turismo.',
    descripcionLarga:
      'Invierte en empresas de entretenimiento digital y turismo internacional.',
    moneda: 'USD',
    riesgo: NivelRiesgo.MEDIO,
    rentabilidadEsperadaAnual: 14,
    liquidezDias: 3,
    montoMinimo: 200,
    destacado: true,
    tags: ['fondo', 'sectorial'],
  },
  {
    id: 'p17',
    nombre: 'Cuenta de Ahorro Joven Digital',
    codigo: 'CASL-01',
    tipo: 'Cuenta de Ahorro',
    descripcionCorta: 'Ahorro con metas y recompensas para jóvenes.',
    descripcionLarga:
      'Incluye ‘sobres’ de ahorro y bonificaciones por disciplina.',
    moneda: 'USD',
    riesgo: NivelRiesgo.BAJO,
    tasaInteresAnual: 1.8,
    liquidezDias: 0,
    montoMinimo: 10,
    destacado: false,
    tags: ['ahorro', 'digital'],
  },
  {
    id: 'p18',
    nombre: 'Pagaré Indexado a Confianza del Consumidor',
    codigo: 'PCI-2024',
    tipo: 'Pagaré',
    descripcionCorta: 'Tasa variable vinculada al ciclo económico.',
    descripcionLarga:
      'Se ajusta según indicadores de confianza del consumidor.',
    moneda: 'USD',
    riesgo: NivelRiesgo.ALTO,
    tasaInteresAnual: 9,
    plazoMeses: 24,
    liquidezDias: 10,
    montoMinimo: 300,
    destacado: false,
    tags: ['pagaré', 'ciclo económico'],
  },
  {
    id: 'p19',
    nombre: 'ETF de Economía Digital y Gaming',
    codigo: 'ETFV-PETS',
    tipo: 'ETF',
    descripcionCorta: 'Inversión en gaming y plataformas digitales.',
    descripcionLarga:
      'Replica un índice de empresas vinculadas al entretenimiento digital.',
    moneda: 'USD',
    riesgo: NivelRiesgo.MEDIO,
    rentabilidadEsperadaAnual: 15,
    liquidezDias: 1,
    montoMinimo: 150,
    destacado: false,
    tags: ['ETF', 'gaming'],
  },
  {
    id: 'p20',
    nombre: 'Derivado sobre Índice de Confianza del Mercado',
    codigo: 'HORO-FX',
    tipo: 'Derivado',
    descripcionCorta: 'Cobertura basada en índices de volatilidad.',
    descripcionLarga:
      'Permite especular o cubrir movimientos en indicadores de confianza del mercado.',
    moneda: 'USD',
    riesgo: NivelRiesgo.ALTO,
    rentabilidadEsperadaAnual: 22,
    liquidezDias: 2,
    montoMinimo: 250,
    destacado: false,
    tags: ['derivado', 'volatilidad'],
  },

  /* 21–30 */
  {
    id: 'p21',
    nombre: 'Crédito Personal de Reinvención Profesional',
    codigo: 'RESET-LIFE',
    tipo: 'Crédito Personal',
    descripcionCorta: 'Financia cambios de carrera y formación.',
    descripcionLarga:
      'Incluye periodos de gracia y opciones flexibles según el empleo del cliente.',
    moneda: 'USD',
    riesgo: NivelRiesgo.ALTO,
    tasaInteresAnual: 13,
    plazoMeses: 120,
    liquidezDias: 0,
    montoMinimo: 5000,
    destacado: false,
    tags: ['crédito', 'educación'],
  },
  {
    id: 'p22',
    nombre: 'Depósito a Plazo con Revisión Trimestral',
    codigo: 'MOON-DP',
    tipo: 'Depósito a Plazo',
    descripcionCorta: 'Depósito con ajustes de tasa trimestrales.',
    descripcionLarga:
      'La tasa se revisa cada trimestre según condiciones de mercado.',
    moneda: 'USD',
    riesgo: NivelRiesgo.BAJO,
    tasaInteresAnual: 3,
    plazoMeses: 6,
    liquidezDias: 7,
    montoMinimo: 200,
    destacado: false,
    tags: ['depósito', 'tasa variable'],
  },
  {
    id: 'p23',
    nombre: 'Bono de Educación y Formación Continua',
    codigo: 'READ-BOND',
    tipo: 'Bono',
    descripcionCorta: 'Renta fija para financiar educación.',
    descripcionLarga:
      'Emisión destinada a proyectos educativos con cupones estables.',
    moneda: 'EUR',
    riesgo: NivelRiesgo.BAJO,
    tasaInteresAnual: 5,
    plazoMeses: 48,
    liquidezDias: 20,
    montoMinimo: 150,
    destacado: true,
    tags: ['bono', 'educación'],
  },
  {
    id: 'p24',
    nombre: 'Fondo de Tecnología Disruptiva Global',
    codigo: 'IMP-TECH',
    tipo: 'Fondo de Inversión',
    descripcionCorta: 'Invierte en IA, biotecnología y automatización.',
    descripcionLarga: 'Alta volatilidad, orientado a perfiles agresivos.',
    moneda: 'USD',
    riesgo: NivelRiesgo.ALTO,
    rentabilidadEsperadaAnual: 27,
    liquidezDias: 5,
    montoMinimo: 1000,
    destacado: true,
    tags: ['tecnología', 'alto riesgo'],
  },
  {
    id: 'p25',
    nombre: 'Índice Cripto de Activos Digitales Temáticos',
    codigo: 'CGT-NFT',
    tipo: 'Criptomoneda',
    descripcionCorta: 'Replica un índice de NFTs y activos digitales.',
    descripcionLarga: 'Muy volátil y especulativo.',
    moneda: 'CGT',
    riesgo: NivelRiesgo.ALTO,
    rentabilidadEsperadaAnual: 35,
    liquidezDias: 0,
    montoMinimo: 5,
    destacado: false,
    tags: ['crypto', 'NFT'],
  },
  {
    id: 'p26',
    nombre: 'Seguro de Ingresos ante Contingencias',
    codigo: 'LUCK-INS',
    tipo: 'Seguro',
    descripcionCorta: 'Renta temporal por desempleo o incapacidad.',
    descripcionLarga:
      'Cubre pérdida parcial de ingresos en eventos inesperados.',
    moneda: 'USD',
    riesgo: NivelRiesgo.BAJO,
    liquidezDias: 3,
    montoMinimo: 120,
    destacado: false,
    tags: ['seguro', 'contingencias'],
  },
  {
    id: 'p27',
    nombre: 'ETF de Industrias Creativas',
    codigo: 'CREA-ETF',
    tipo: 'ETF',
    descripcionCorta: 'Invierte en diseño, medios y contenido digital.',
    descripcionLarga: 'Sector creativo global con exposición diversificada.',
    moneda: 'USD',
    riesgo: NivelRiesgo.MEDIO,
    rentabilidadEsperadaAnual: 12,
    liquidezDias: 1,
    montoMinimo: 180,
    destacado: false,
    tags: ['ETF', 'creatividad'],
  },
  {
    id: 'p28',
    nombre: 'Swap de Índice de Bienestar Corporativo',
    codigo: 'FIT-SWAP',
    tipo: 'Derivado',
    descripcionCorta: 'Basado en métricas de bienestar laboral.',
    descripcionLarga:
      'Herramienta para cubrir cambios en retención de empleados y clima laboral.',
    moneda: 'USD',
    riesgo: NivelRiesgo.MEDIO,
    rentabilidadEsperadaAnual: 8,
    liquidezDias: 4,
    montoMinimo: 250,
    destacado: false,
    tags: ['derivado', 'RRHH'],
  },
  {
    id: 'p29',
    nombre: 'Plan de Patrimonio Familiar Integral',
    codigo: 'STORY-PLAN',
    tipo: 'Plan',
    descripcionCorta: 'Ahorro + inversión + seguros en un solo paquete.',
    descripcionLarga:
      'Solución estructurada para construcción y protección patrimonial.',
    moneda: 'USD',
    riesgo: NivelRiesgo.BAJO,
    tasaInteresAnual: 4,
    plazoMeses: 120,
    liquidezDias: 10,
    montoMinimo: 300,
    destacado: false,
    tags: ['patrimonio', 'integral'],
  },
  {
    id: 'p30',
    nombre: 'Certificado de Serenidad Financiera',
    codigo: 'SEREN-CERT',
    tipo: 'Certificado',
    descripcionCorta: 'Certificado conservador de corto plazo.',
    descripcionLarga:
      'Renta fija estable para perfiles que priorizan seguridad y liquidez moderada.',
    moneda: 'USD',
    riesgo: NivelRiesgo.BAJO,
    tasaInteresAnual: 3.7,
    plazoMeses: 12,
    liquidezDias: 5,
    montoMinimo: 250,
    destacado: true,
    tags: ['certificado', 'conservador'],
  },

  /* Créditos personales p31–p36 */
  {
    id: 'p31',
    nombre: 'Crédito Personal Rápido Online',
    codigo: 'CP-FAST',
    tipo: 'Crédito Personal',
    descripcionCorta: 'Aprobación inmediata y desembolso en minutos.',
    descripcionLarga:
      'Diseñado para emergencias o gastos imprevistos. Proceso 100% digital.',
    moneda: 'USD',
    riesgo: NivelRiesgo.ALTO,
    tasaInteresAnual: 21,
    plazoMeses: 36,
    liquidezDias: 0,
    montoMinimo: 1000,
    destacado: true,
    tags: ['crédito', 'rápido', 'digital'],
  },
  {
    id: 'p32',
    nombre: 'Crédito Personal Educativo',
    codigo: 'CP-EDU',
    tipo: 'Crédito Personal',
    descripcionCorta: 'Préstamo para estudios superiores.',
    descripcionLarga: 'Incluye periodos de gracia mientras el usuario estudia.',
    moneda: 'USD',
    riesgo: NivelRiesgo.MEDIO,
    tasaInteresAnual: 12,
    plazoMeses: 72,
    liquidezDias: 0,
    montoMinimo: 2000,
    destacado: false,
    tags: ['crédito', 'educación'],
  },
  {
    id: 'p33',
    nombre: 'Crédito Personal para Renovación del Hogar',
    codigo: 'CP-HOME',
    tipo: 'Crédito Personal',
    descripcionCorta: 'Financia remodelaciones y mejoras domésticas.',
    descripcionLarga: 'Desembolso por etapas opcional para proyectos grandes.',
    moneda: 'USD',
    riesgo: NivelRiesgo.MEDIO,
    tasaInteresAnual: 15,
    plazoMeses: 60,
    liquidezDias: 0,
    montoMinimo: 3000,
    destacado: false,
    tags: ['crédito', 'hogar'],
  },
  {
    id: 'p34',
    nombre: 'Crédito Personal Salud y Bienestar',
    codigo: 'CP-HEALTH',
    tipo: 'Crédito Personal',
    descripcionCorta: 'Financia tratamientos médicos o terapias.',
    descripcionLarga: 'Convenios con clínicas afiliadas y tasas preferentes.',
    moneda: 'USD',
    riesgo: NivelRiesgo.MEDIO,
    tasaInteresAnual: 10,
    plazoMeses: 48,
    liquidezDias: 0,
    montoMinimo: 1500,
    destacado: true,
    tags: ['crédito', 'salud'],
  },
  {
    id: 'p35',
    nombre: 'Crédito Personal Emprendedor',
    codigo: 'CP-START',
    tipo: 'Crédito Personal',
    descripcionCorta: 'Financia inventario, equipos y marketing.',
    descripcionLarga: 'Diseñado para microemprendedores con asesoría opcional.',
    moneda: 'USD',
    riesgo: NivelRiesgo.ALTO,
    tasaInteresAnual: 19,
    plazoMeses: 48,
    liquidezDias: 0,
    montoMinimo: 2500,
    destacado: false,
    tags: ['crédito', 'emprendimiento'],
  },
  {
    id: 'p36',
    nombre: 'Crédito Personal Consolidación de Deuda',
    codigo: 'CP-CONSOL',
    tipo: 'Crédito Personal',
    descripcionCorta: 'Unifica deudas en un solo pago mensual.',
    descripcionLarga: 'Permite mejorar flujo de caja y obtener mejores tasas.',
    moneda: 'USD',
    riesgo: NivelRiesgo.MEDIO,
    tasaInteresAnual: 14,
    plazoMeses: 84,
    liquidezDias: 0,
    montoMinimo: 3000,
    destacado: true,
    tags: ['crédito', 'consolidación'],
  },

  /* Tarjetas de crédito p37–p42 */
  {
    id: 'p37',
    nombre: 'Tarjeta de Crédito Clásica',
    codigo: 'TC-CLASSIC',
    tipo: 'Tarjeta de Crédito',
    descripcionCorta: 'Baja comisión y beneficios esenciales.',
    descripcionLarga: 'Ideal para usuarios con historial crediticio inicial.',
    moneda: 'USD',
    riesgo: NivelRiesgo.MEDIO,
    tasaInteresAnual: 28,
    liquidezDias: 0,
    montoMinimo: 0,
    destacado: false,
    tags: ['tarjeta', 'clásica'],
  },
  {
    id: 'p38',
    nombre: 'Tarjeta de Crédito Gold Rewards',
    codigo: 'TC-GOLD',
    tipo: 'Tarjeta de Crédito',
    descripcionCorta: 'Programa de puntos y beneficios premium.',
    descripcionLarga: 'Cashback, seguros de viaje y eventos exclusivos.',
    moneda: 'USD',
    riesgo: NivelRiesgo.MEDIO,
    tasaInteresAnual: 26,
    liquidezDias: 0,
    montoMinimo: 0,
    destacado: true,
    tags: ['tarjeta', 'gold'],
  },
  {
    id: 'p39',
    nombre: 'Tarjeta de Crédito Platinum Travel',
    codigo: 'TC-PLAT',
    tipo: 'Tarjeta de Crédito',
    descripcionCorta: 'Beneficios de viajes internacionales.',
    descripcionLarga:
      'Acceso a salas VIP, millas aceleradas y seguros ampliados.',
    moneda: 'USD',
    riesgo: NivelRiesgo.MEDIO,
    tasaInteresAnual: 24,
    liquidezDias: 0,
    montoMinimo: 0,
    destacado: true,
    tags: ['tarjeta', 'viajes'],
  },
  {
    id: 'p40',
    nombre: 'Tarjeta de Crédito Cashback Total',
    codigo: 'TC-CASH',
    tipo: 'Tarjeta de Crédito',
    descripcionCorta: 'Cashback del 1% al 3% en compras.',
    descripcionLarga:
      'Reembolsos sin límites y bonificaciones en supermercados.',
    moneda: 'USD',
    riesgo: NivelRiesgo.MEDIO,
    tasaInteresAnual: 27,
    liquidezDias: 0,
    montoMinimo: 0,
    destacado: false,
    tags: ['tarjeta', 'cashback'],
  },
  {
    id: 'p41',
    nombre: 'Tarjeta de Crédito Zero Cuotas',
    codigo: 'TC-ZERO',
    tipo: 'Tarjeta de Crédito',
    descripcionCorta: 'Sin anualidad y cuotas sin interés.',
    descripcionLarga: 'Tarjeta 100% digital enfocada en jóvenes usuarios.',
    moneda: 'USD',
    riesgo: NivelRiesgo.ALTO,
    tasaInteresAnual: 31,
    liquidezDias: 0,
    montoMinimo: 0,
    destacado: false,
    tags: ['tarjeta', 'sin anualidad'],
  },
  {
    id: 'p42',
    nombre: 'Tarjeta de Crédito Elite Signature',
    codigo: 'TC-ELITE',
    tipo: 'Tarjeta de Crédito',
    descripcionCorta: 'Concierge 24/7 y beneficios de lujo.',
    descripcionLarga: 'Acceso ilimitado a salas VIP y millas premium.',
    moneda: 'USD',
    riesgo: NivelRiesgo.MEDIO,
    tasaInteresAnual: 22,
    liquidezDias: 0,
    montoMinimo: 0,
    destacado: true,
    tags: ['tarjeta', 'elite', 'lujo'],
  },
];
