import { NivelRiesgo, Product } from '../entities/product.entity';

export const PRODUCTS: Product[] = [
  {
    id: 'a1',
    nombre: 'Plan de Ahorro Flexible',
    codigo: 'AHO-FLEX',
    tipo: 'Producto de Ahorro',
    descripcionCorta: 'Ahorro con aportes libres y retiros parciales.',
    descripcionLarga:
      'Producto de ahorro que permite realizar aportes en cualquier momento y retirar parcialmente los fondos sin penalización significativa, manteniendo una rentabilidad moderada.',
    moneda: 'USD',
    riesgo: NivelRiesgo.BAJO,
    tasaInteresAnual: 2.2,
    liquidezDias: 2,
    montoMinimo: 100,
    destacado: false,
    tags: ['ahorro', 'flexible', 'liquidez'],
  },
  {
    id: 'a2',
    nombre: 'Plan de Ahorro Programado',
    codigo: 'AHO-PROG',
    tipo: 'Producto de Ahorro',
    descripcionCorta: 'Ahorro automático con aportes periódicos.',
    descripcionLarga:
      'Diseñado para clientes que desean ahorrar de forma disciplinada mediante aportes mensuales automáticos. Ofrece una mejor tasa a cambio de permanencia.',
    moneda: 'USD',
    riesgo: NivelRiesgo.BAJO,
    tasaInteresAnual: 3.0,
    liquidezDias: 30,
    montoMinimo: 50,
    destacado: true,
    tags: ['ahorro', 'programado', 'disciplina'],
  },
  {
    id: 'a3',
    nombre: 'Certificado de Ahorro a Plazo Fijo 12 Meses',
    codigo: 'AHO-CERT-12',
    tipo: 'Certificado de Ahorro',
    descripcionCorta: 'Tasa fija garantizada a 12 meses.',
    descripcionLarga:
      'Instrumento de ahorro de plazo fijo que ofrece una tasa de interés garantizada al vencimiento. No permite retiros anticipados sin penalización.',
    moneda: 'USD',
    riesgo: NivelRiesgo.BAJO,
    tasaInteresAnual: 3.8,
    plazoMeses: 12,
    liquidezDias: 90,
    montoMinimo: 500,
    destacado: false,
    tags: ['ahorro', 'plazo fijo', 'tasa fija'],
  },
  {
    id: 'a4',
    nombre: 'Certificado de Ahorro a Plazo Fijo 24 Meses',
    codigo: 'AHO-CERT-24',
    tipo: 'Certificado de Ahorro',
    descripcionCorta: 'Mayor rentabilidad por mayor plazo.',
    descripcionLarga:
      'Certificado de ahorro con plazo extendido que ofrece una tasa superior a cambio de mantener el capital invertido durante 24 meses.',
    moneda: 'USD',
    riesgo: NivelRiesgo.BAJO,
    tasaInteresAnual: 4.2,
    plazoMeses: 24,
    liquidezDias: 120,
    montoMinimo: 500,
    destacado: true,
    tags: ['ahorro', 'plazo fijo', 'mediano plazo'],
  },
  {
    id: 'a5',
    nombre: 'Plan de Ahorro para Objetivos',
    codigo: 'AHO-GOALS',
    tipo: 'Producto de Ahorro',
    descripcionCorta: 'Ahorro orientado a metas específicas.',
    descripcionLarga:
      'Permite definir objetivos concretos como viajes, educación o fondo de emergencia, con seguimiento del progreso y bonificaciones por cumplimiento.',
    moneda: 'USD',
    riesgo: NivelRiesgo.BAJO,
    tasaInteresAnual: 2.7,
    liquidezDias: 15,
    montoMinimo: 100,
    destacado: false,
    tags: ['ahorro', 'objetivos', 'planificación'],
  },
  {
    id: 'a6',
    nombre: 'Plan de Ahorro Conservador Indexado',
    codigo: 'AHO-IDX',
    tipo: 'Producto de Ahorro',
    descripcionCorta: 'Rentabilidad ajustada a tasa de referencia.',
    descripcionLarga:
      'Producto de ahorro de bajo riesgo cuya tasa se ajusta periódicamente según una referencia de mercado, manteniendo estabilidad del capital.',
    moneda: 'USD',
    riesgo: NivelRiesgo.BAJO,
    tasaInteresAnual: 2.9,
    liquidezDias: 7,
    montoMinimo: 300,
    destacado: false,
    tags: ['ahorro', 'indexado', 'conservador'],
  },
  {
    id: 'a7',
    nombre: 'Plan de Ahorro a Largo Plazo',
    codigo: 'AHO-LP',
    tipo: 'Producto de Ahorro',
    descripcionCorta: 'Ahorro estructurado para horizonte largo.',
    descripcionLarga:
      'Diseñado para clientes que buscan acumular capital a varios años mediante aportes periódicos y una tasa preferencial por permanencia.',
    moneda: 'USD',
    riesgo: NivelRiesgo.BAJO,
    tasaInteresAnual: 4.0,
    plazoMeses: 60,
    liquidezDias: 60,
    montoMinimo: 1000,
    destacado: true,
    tags: ['ahorro', 'largo plazo', 'capitalización'],
  },
  {
    id: 'a8',
    nombre: 'Plan de Ahorro Premium',
    codigo: 'AHO-PREM',
    tipo: 'Producto de Ahorro',
    descripcionCorta: 'Ahorro con tasa preferencial para montos elevados.',
    descripcionLarga:
      'Producto orientado a clientes con mayor capacidad de ahorro. Ofrece tasas preferenciales y condiciones mejoradas a cambio de menor liquidez.',
    moneda: 'USD',
    riesgo: NivelRiesgo.BAJO,
    tasaInteresAnual: 4.5,
    plazoMeses: 36,
    liquidezDias: 45,
    montoMinimo: 5000,
    destacado: true,
    tags: ['ahorro', 'premium', 'alto monto'],
  },
  {
    id: 'a9',
    nombre: 'Plan de Ahorro Escalonado',
    codigo: 'AHO-STEP',
    tipo: 'Producto de Ahorro',
    descripcionCorta: 'La tasa mejora cuanto más tiempo permaneces.',
    descripcionLarga:
      'Producto de ahorro sin plazo fijo donde la tasa de interés aumenta por tramos según la antigüedad del ahorro.',
    moneda: 'USD',
    riesgo: NivelRiesgo.BAJO,
    tasaInteresAnual: 3.1,
    liquidezDias: 10,
    montoMinimo: 200,
    destacado: false,
    tags: ['ahorro', 'escalonado'],
  },
  {
    id: 'a10',
    nombre: 'Plan de Ahorro con Bonificación Anual',
    codigo: 'AHO-BONUS',
    tipo: 'Producto de Ahorro',
    descripcionCorta: 'Bonificación extra por permanencia anual.',
    descripcionLarga:
      'Otorga una bonificación adicional de interés al cierre de cada año si no se realizan retiros durante el período.',
    moneda: 'USD',
    riesgo: NivelRiesgo.BAJO,
    tasaInteresAnual: 3.3,
    liquidezDias: 30,
    montoMinimo: 300,
    destacado: false,
    tags: ['ahorro', 'bonificación'],
  },
  {
    id: 'a11',
    nombre: 'Producto de Ahorro de Alta Liquidez',
    codigo: 'AHO-LIQ',
    tipo: 'Producto de Ahorro',
    descripcionCorta: 'Acceso rápido a los fondos con rentabilidad básica.',
    descripcionLarga:
      'Pensado para clientes que priorizan disponibilidad inmediata del dinero con una tasa superior a cuentas tradicionales.',
    moneda: 'USD',
    riesgo: NivelRiesgo.BAJO,
    tasaInteresAnual: 1.9,
    liquidezDias: 1,
    montoMinimo: 50,
    destacado: false,
    tags: ['ahorro', 'liquidez'],
  },
  {
    id: 'a12',
    nombre: 'Plan de Ahorro Previsional Complementario',
    codigo: 'AHO-PREV',
    tipo: 'Producto de Ahorro',
    descripcionCorta: 'Ahorro de largo plazo para complementar la jubilación.',
    descripcionLarga:
      'Producto orientado al ahorro previsional con incentivos por permanencia y horizonte de largo plazo.',
    moneda: 'USD',
    riesgo: NivelRiesgo.BAJO,
    tasaInteresAnual: 4.1,
    plazoMeses: 120,
    liquidezDias: 90,
    montoMinimo: 500,
    destacado: true,
    tags: ['ahorro', 'previsión', 'largo plazo'],
  },
  {
    id: 'a13',
    nombre: 'CDT Tradicional 90 Días',
    codigo: 'CDT-90D',
    tipo: 'CDT',
    descripcionCorta: 'Inversión a corto plazo con tasa fija.',
    descripcionLarga:
      'Certificado de Depósito a Término (CDT) a 90 días con tasa fija y pago de rendimientos al vencimiento. No permite retiro anticipado sin penalización.',
    moneda: 'COP',
    riesgo: NivelRiesgo.BAJO,
    tasaInteresAnual: 10.5,
    plazoMeses: 3,
    liquidezDias: 90,
    montoMinimo: 500000,
    destacado: true,
    tags: ['inversión', 'cdt', 'tasa fija', 'corto plazo'],
  },
  {
    id: 'a14',
    nombre: 'CDT Tradicional 180 Días',
    codigo: 'CDT-180D',
    tipo: 'CDT',
    descripcionCorta: 'CDT de mediano plazo con tasa fija.',
    descripcionLarga:
      'CDT a 180 días con rendimientos al vencimiento. Adecuado para excedentes de liquidez que pueden mantenerse sin retiros.',
    moneda: 'COP',
    riesgo: NivelRiesgo.BAJO,
    tasaInteresAnual: 11.2,
    plazoMeses: 6,
    liquidezDias: 180,
    montoMinimo: 500000,
    destacado: false,
    tags: ['inversión', 'cdt', 'mediano plazo'],
  },
  {
    id: 'a15',
    nombre: 'CDT en USD 12 Meses',
    codigo: 'CDT-USD-12M',
    tipo: 'CDT',
    descripcionCorta: 'CDT en dólares con tasa fija anual.',
    descripcionLarga:
      'CDT denominado en USD a 12 meses. Pensado para clientes que desean diversificar moneda manteniendo un perfil conservador.',
    moneda: 'USD',
    riesgo: NivelRiesgo.BAJO,
    tasaInteresAnual: 4.8,
    plazoMeses: 12,
    liquidezDias: 365,
    montoMinimo: 1000,
    destacado: false,
    tags: ['inversión', 'cdt', 'usd', 'diversificación'],
  },
  {
    id: 'a16',
    nombre: 'CDT en EUR 12 Meses',
    codigo: 'CDT-EUR-12M',
    tipo: 'CDT',
    descripcionCorta: 'CDT en euros con tasa fija anual.',
    descripcionLarga:
      'CDT denominado en EUR a 12 meses. Alternativa conservadora para diversificación cambiaria.',
    moneda: 'EUR',
    riesgo: NivelRiesgo.BAJO,
    tasaInteresAnual: 3.9,
    plazoMeses: 12,
    liquidezDias: 365,
    montoMinimo: 900,
    destacado: false,
    tags: ['inversión', 'cdt', 'eur', 'tasa fija'],
  },
  {
    id: 'a17',
    nombre: 'Depósito a Plazo Renovable Mensual',
    codigo: 'DP-REN-M',
    tipo: 'Depósito a Plazo',
    descripcionCorta: 'Plazo corto con renovación automática.',
    descripcionLarga:
      'Depósito con vencimientos mensuales que se renueva automáticamente. Permite mantener flexibilidad sin sacrificar totalmente la rentabilidad.',
    moneda: 'MXN',
    riesgo: NivelRiesgo.BAJO,
    tasaInteresAnual: 9.0,
    plazoMeses: 1,
    liquidezDias: 30,
    montoMinimo: 2000,
    destacado: false,
    tags: ['ahorro', 'depósito', 'renovable', 'corto plazo'],
  },
  {
    id: 'a18',
    nombre: 'Depósito a Plazo en EUR 6 Meses',
    codigo: 'DP-EUR-6M',
    tipo: 'Depósito a Plazo',
    descripcionCorta: 'Depósito en euros con tasa fija a 6 meses.',
    descripcionLarga:
      'Depósito a plazo fijo en EUR con pago de rendimientos al vencimiento. Recomendado para clientes que desean mantener exposición en euros.',
    moneda: 'EUR',
    riesgo: NivelRiesgo.BAJO,
    tasaInteresAnual: 3.2,
    plazoMeses: 6,
    liquidezDias: 180,
    montoMinimo: 500,
    destacado: false,
    tags: ['ahorro', 'depósito', 'eur', 'tasa fija'],
  },
  {
    id: 'a19',
    nombre: 'Fondo Money Market Conservador',
    codigo: 'FMM-CONS',
    tipo: 'Fondo de Inversión',
    descripcionCorta: 'Fondo de liquidez con instrumentos de muy bajo riesgo.',
    descripcionLarga:
      'Fondo orientado a preservación de capital y liquidez, invierte en instrumentos de corto plazo como pagarés y depósitos bancarios. Puede tener variación leve en el valor cuota.',
    moneda: 'USD',
    riesgo: NivelRiesgo.BAJO,
    tasaInteresAnual: 3.6,
    liquidezDias: 1,
    montoMinimo: 100,
    destacado: true,
    tags: ['inversión', 'money market', 'liquidez', 'conservador'],
  },
  {
    id: 'a20',
    nombre: 'Fondo de Renta Fija Corto Plazo',
    codigo: 'RF-CP',
    tipo: 'Fondo de Inversión',
    descripcionCorta: 'Renta fija de corto plazo para perfiles conservadores.',
    descripcionLarga:
      'Invierte principalmente en bonos de corta duración y alta calidad crediticia. Busca estabilidad con mejor rendimiento que productos a la vista.',
    moneda: 'COP',
    riesgo: NivelRiesgo.BAJO,
    tasaInteresAnual: 9.2,
    liquidezDias: 2,
    montoMinimo: 200000,
    destacado: false,
    tags: ['inversión', 'renta fija', 'corto plazo'],
  },
];
